server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false



